import Foundation

public enum AuthorizationStatus:String,Codable,CaseIterable,Sendable { case draft="Draft", submitted="Submitted", approved="Approved", active="Active", suspended="Suspended", closed="Closed" }
public struct AuthorizationSignature:Identifiable,Codable,Equatable,Sendable { public let id:String; public var role:String; public var person:String; public var signedAt:Date?; public var accepted:Bool; public init(id:String,role:String,person:String="",signedAt:Date?=nil,accepted:Bool=false){self.id=id;self.role=role;self.person=person;self.signedAt=signedAt;self.accepted=accepted} }
public struct PermitToEnergize:Identifiable,Codable,Equatable,Sendable { public let id:String; public var number:String; public var equipment:[String]; public var voltage:String; public var boundaries:String; public var prerequisites:[String:Bool]; public var signatures:[AuthorizationSignature]; public var status:AuthorizationStatus; public var issuedAt:Date?; public var expiresAt:Date?; public var allPrerequisitesMet:Bool{!prerequisites.isEmpty && prerequisites.values.allSatisfy{$0}}; public var fullyAuthorized:Bool{allPrerequisitesMet && !signatures.isEmpty && signatures.allSatisfy{$0.accepted}} }
public struct IsolationPoint:Identifiable,Codable,Equatable,Sendable { public let id:String; public var tag:String; public var energyType:String; public var location:String; public var normalState:String; public var isolated:Bool; public var locked:Bool; public var zeroEnergyVerified:Bool }
public struct LOTOAuthorization:Identifiable,Codable,Equatable,Sendable { public let id:String; public var equipment:String; public var points:[IsolationPoint]; public var authorizedPerson:String; public var affectedPersonsNotified:Bool; public var restorationInspectionPassed:Bool; public var status:AuthorizationStatus; public var safeForWork:Bool{!points.isEmpty && points.allSatisfy{$0.isolated && $0.locked && $0.zeroEnergyVerified} && affectedPersonsNotified}; public var readyForRestoration:Bool{restorationInspectionPassed && points.allSatisfy{$0.zeroEnergyVerified}} }

public enum OperationalRecordStatus:String,Codable,CaseIterable,Sendable { case notStarted="Not started", inProgress="In progress", passed="Passed", failed="Failed", accepted="Accepted" }
public struct LoopCheckPoint:Identifiable,Codable,Equatable,Sendable { public let id:String; public var loopTag:String; public var fieldDevice:String; public var terminal:String; public var plcAddress:String; public var hmiTag:String; public var stimulus:String; public var expected:String; public var observed:String; public var status:OperationalRecordStatus; public var evidence:String }
public struct OperationalCalibrationPoint:Identifiable,Codable,Equatable,Sendable { public let id:String; public var inputPercent:Double; public var reference:Double; public var indicated:Double; public var errorPercentSpan:Double }
public struct InstrumentCalibrationCertificate:Identifiable,Codable,Equatable,Sendable { public let id:String; public var certificateNumber:String; public var instrumentTag:String; public var range:String; public var units:String; public var standardID:String; public var standardDueDate:Date; public var asFound:[OperationalCalibrationPoint]; public var asLeft:[OperationalCalibrationPoint]; public var tolerancePercentSpan:Double; public var technician:String; public var status:OperationalRecordStatus; public var asLeftPasses:Bool{!asLeft.isEmpty && asLeft.allSatisfy{abs($0.errorPercentSpan)<=tolerancePercentSpan}} }
public struct MotorSoloRunSheet:Identifiable,Codable,Equatable,Sendable { public let id:String; public var motorTag:String; public var drivenEquipment:String; public var uncoupledOrSafeToRun:Bool; public var rotationCorrect:Bool; public var currentA:[Double]; public var vibrationMMs:Double?; public var bearingTempC:Double?; public var runMinutes:Int; public var status:OperationalRecordStatus; public var passes:Bool{uncoupledOrSafeToRun && rotationCorrect && currentA.count==3 && runMinutes>=5 && status == .passed} }

public struct StartupShiftLogEntry:Identifiable,Codable,Equatable,Sendable { public let id:String; public var timestamp:Date; public var shift:String; public var stage:PlantStartupStage; public var author:String; public var event:String; public var action:String; public var handoff:String; public var critical:Bool }
public struct OperatorTrainingSignoff:Identifiable,Codable,Equatable,Sendable { public let id:String; public var trainee:String; public var module:String; public var demonstrated:[String:Bool]; public var trainer:String; public var signedAt:Date?; public var passed:Bool{!demonstrated.isEmpty && demonstrated.values.allSatisfy{$0} && signedAt != nil} }
public struct SparePartTurnoverItem:Identifiable,Codable,Equatable,Sendable { public let id:String; public var partNumber:String; public var description:String; public var requiredQuantity:Int; public var receivedQuantity:Int; public var storageLocation:String; public var verified:Bool; public var complete:Bool{verified && receivedQuantity>=requiredQuantity} }
public struct MaintenanceHandover:Identifiable,Codable,Equatable,Sendable { public let id:String; public var pmTasks:[String:Bool]; public var backupsVerified:Bool; public var manualsDelivered:Bool; public var trainingComplete:Bool; public var cmmsAssetsCreated:Bool; public var acceptedBy:String; public var acceptedAt:Date?; public var complete:Bool{!pmTasks.isEmpty && pmTasks.values.allSatisfy{$0} && backupsVerified && manualsDelivered && trainingComplete && cmmsAssetsCreated && acceptedAt != nil} }

public struct TurnoverPackage:Identifiable,Codable,Equatable,Sendable { public let id:String; public var packageNumber:String; public var requiredSections:[String:Bool]; public var approvers:[AuthorizationSignature]; public var accepted:Bool{!requiredSections.isEmpty && requiredSections.values.allSatisfy{$0} && approvers.allSatisfy{$0.accepted}} }
public struct DocumentationBookSection:Identifiable,Codable,Equatable,Sendable { public let id:String; public var title:String; public var documentReferences:[String]; public var complete:Bool }
public struct FinalDocumentationBook:Identifiable,Codable,Equatable,Sendable { public let id:String; public var projectNumber:String; public var revision:String; public var sections:[DocumentationBookSection]; public var generatedAt:Date; public var completionPercent:Double{guard !sections.isEmpty else{return 0};return Double(sections.filter{$0.complete}.count)/Double(sections.count)*100} }

public enum CampaignFaultTrigger:String,Codable,CaseIterable,Sendable { case startOfDay, afterEnergization, afterFirstRun, afterWarmup, duringProduction, shiftHandoff }
public struct CampaignFaultEvent:Identifiable,Codable,Equatable,Sendable { public let id:String; public var day:Int; public var trigger:CampaignFaultTrigger; public var stage:PlantStartupStage; public var fault:InstructorMiswire; public var briefing:String; public var revealed:Bool; public var resolved:Bool }
public struct StartupCampaignDay:Identifiable,Codable,Equatable,Sendable { public let id:String; public var day:Int; public var title:String; public var objective:String; public var targetStage:PlantStartupStage; public var requiredRecords:[String]; public var faultEventIDs:[String] }
public struct MultiDayStartupCampaign:Identifiable,Codable,Equatable,Sendable { public let id:String; public var title:String; public var days:[StartupCampaignDay]; public var faults:[CampaignFaultEvent]; public var currentDay:Int; public var instructorSeed:Int; public var score:Int; public mutating func reveal(trigger:CampaignFaultTrigger,stage:PlantStartupStage)->[CampaignFaultEvent]{var out:[CampaignFaultEvent]=[];for i in faults.indices where faults[i].day==currentDay && faults[i].trigger==trigger && faults[i].stage==stage && !faults[i].revealed { faults[i].revealed=true;out.append(faults[i]) };return out} }

public struct OperationalCommissioningPackage:Codable,Equatable,Sendable {
 public var permit:PermitToEnergize; public var loto:LOTOAuthorization; public var loopChecks:[LoopCheckPoint]; public var calibrations:[InstrumentCalibrationCertificate]; public var motorRuns:[MotorSoloRunSheet]; public var turnover:TurnoverPackage; public var shiftLog:[StartupShiftLogEntry]; public var training:[OperatorTrainingSignoff]; public var spares:[SparePartTurnoverItem]; public var maintenance:MaintenanceHandover; public var campaign:MultiDayStartupCampaign
 public var readyToEnergize:Bool { permit.fullyAuthorized && loopChecks.filter{$0.status != .passed}.isEmpty && calibrations.allSatisfy{$0.asLeftPasses} && motorRuns.allSatisfy{$0.passes} }
 public var readyForFinalTurnover:Bool { turnover.accepted && training.allSatisfy{$0.passed} && spares.allSatisfy{$0.complete} && maintenance.complete }
 public func finalBook(projectNumber:String,revision:String)->FinalDocumentationBook { let sections=[
  DocumentationBookSection(id:"DOC-DWG",title:"As-built drawings",documentReferences:["Electrical CAD As-Built Rev \(revision)"],complete:true),
  .init(id:"DOC-PERMIT",title:"Energization permits and LOTO",documentReferences:[permit.number,loto.id],complete:permit.status == .closed && loto.status == .closed),
  .init(id:"DOC-LOOPS",title:"Loop checks and calibration certificates",documentReferences:loopChecks.map(\.id)+calibrations.map(\.certificateNumber),complete:loopChecks.allSatisfy{$0.status == .passed} && calibrations.allSatisfy{$0.asLeftPasses}),
  .init(id:"DOC-MOTOR",title:"Motor solo-run records",documentReferences:motorRuns.map(\.id),complete:motorRuns.allSatisfy{$0.passes}),
  .init(id:"DOC-TURN",title:"Commissioning turnover",documentReferences:[turnover.packageNumber],complete:turnover.accepted),
  .init(id:"DOC-OPS",title:"Operator training and startup logs",documentReferences:training.map(\.id)+shiftLog.map(\.id),complete:training.allSatisfy{$0.passed} && !shiftLog.isEmpty),
  .init(id:"DOC-MAINT",title:"Spares and maintenance handover",documentReferences:spares.map(\.partNumber)+[maintenance.id],complete:spares.allSatisfy{$0.complete} && maintenance.complete)
 ]; return .init(id:"FDB-\(projectNumber)",projectNumber:projectNumber,revision:revision,sections:sections,generatedAt:Date()) }
}

public enum OperationalCommissioningCatalog {
 public static var trainingPackage:OperationalCommissioningPackage {
  let sigs=[AuthorizationSignature(id:"SIG-OPS",role:"Operations"),.init(id:"SIG-ELEC",role:"Electrical Authorized Person"),.init(id:"SIG-COMM",role:"Commissioning Lead")]
  let permit=PermitToEnergize(id:"PTE-001",number:"PTE-2026-001",equipment:["CP-101","M1","VFD-101"],voltage:"480 VAC / 120 VAC / 24 VDC",boundaries:"Packaging Cell CP-101 through field disconnects",prerequisites:["IFC/field changes reconciled":false,"FAT/SAT complete":false,"A-punch closed":false,"Safety proof complete":false,"LOTO restoration authorized":false],signatures:sigs,status:.draft)
  let loto=LOTOAuthorization(id:"LOTO-001",equipment:"Packaging Cell CP-101 / M1",points:[.init(id:"ISO-1",tag:"DS-101",energyType:"480 VAC",location:"CP-101 door",normalState:"ON",isolated:false,locked:false,zeroEnergyVerified:false),.init(id:"ISO-2",tag:"AIR-101",energyType:"Pneumatic",location:"Cell inlet",normalState:"OPEN",isolated:false,locked:false,zeroEnergyVerified:false)],authorizedPerson:"",affectedPersonsNotified:false,restorationInspectionPassed:false,status:.draft)
  let loops=[LoopCheckPoint(id:"LC-PE203",loopTag:"PE203",fieldDevice:"PE203 photoeye",terminal:"TB1:11",plcAddress:"Local:2:I.Data[0]",hmiTag:"PE203",stimulus:"Block/unblock sensor",expected:"PLC/HMI follows field state",observed:"",status:.notStarted,evidence:""),.init(id:"LC-PT101",loopTag:"PT101",fieldDevice:"Pressure transmitter",terminal:"TB2:3-4",plcAddress:"Local:3:I.Ch0Data",hmiTag:"PT101_PV",stimulus:"0/50/100% source",expected:"Scaled indication within tolerance",observed:"",status:.notStarted,evidence:"")]
  let pts=[0.0,50,100].enumerated().map{OperationalCalibrationPoint(id:"CP-\($0.offset)",inputPercent:$0.element,reference:$0.element,indicated:$0.element,errorPercentSpan:0)}
  let cal=InstrumentCalibrationCertificate(id:"CAL-PT101",certificateNumber:"CAL-2026-001",instrumentTag:"PT101",range:"0-100",units:"psi",standardID:"DPI-001",standardDueDate:Date().addingTimeInterval(86400*180),asFound:pts,asLeft:pts,tolerancePercentSpan:0.5,technician:"",status:.notStarted)
  let motor=MotorSoloRunSheet(id:"MSR-M1",motorTag:"M1",drivenEquipment:"Main conveyor",uncoupledOrSafeToRun:false,rotationCorrect:false,currentA:[],vibrationMMs:nil,bearingTempC:nil,runMinutes:0,status:.notStarted)
  let turnover=TurnoverPackage(id:"TOP-001",packageNumber:"CTO-2026-001",requiredSections:["Approved as-builts":false,"FAT/SAT":false,"Loop/calibration":false,"Backups":false,"Punch/NCR status":false,"Training":false,"Spares":false],approvers:[.init(id:"TOP-OPS",role:"Operations"),.init(id:"TOP-MAINT",role:"Maintenance"),.init(id:"TOP-PROJ",role:"Project")])
  let training=[OperatorTrainingSignoff(id:"TRN-OPS-1",trainee:"",module:"Packaging Cell Operations",demonstrated:["Normal start/stop":false,"Alarm response":false,"E-stop recovery":false,"Manual mode":false],trainer:"",signedAt:nil)]
  let spares=[SparePartTurnoverItem(id:"SP-1",partNumber:"SEN-PE-24V",description:"Photoeye spare",requiredQuantity:2,receivedQuantity:0,storageLocation:"",verified:false),.init(id:"SP-2",partNumber:"FUSE-2A",description:"2 A control fuse",requiredQuantity:10,receivedQuantity:0,storageLocation:"",verified:false)]
  let maint=MaintenanceHandover(id:"MH-001",pmTasks:["Inspect enclosure filters":false,"Check terminal torque":false,"Back up PLC/HMI/VFD":false],backupsVerified:false,manualsDelivered:false,trainingComplete:false,cmmsAssetsCreated:false,acceptedBy:"",acceptedAt:nil)
  let bank=ElectricalCADProjectCatalog.instructorFaultBank
  let faults=[CampaignFaultEvent(id:"CF-1",day:1,trigger:.startOfDay,stage:.installation,fault:bank[0],briefing:"Field crew reports an unexplained I/O discrepancy during loop checks.",revealed:false,resolved:false),.init(id:"CF-2",day:2,trigger:.afterEnergization,stage:.energized,fault:bank[min(1,bank.count-1)],briefing:"A control indication disagrees immediately after first energization.",revealed:false,resolved:false),.init(id:"CF-3",day:3,trigger:.afterWarmup,stage:.hotCommissioning,fault:bank[min(2,bank.count-1)],briefing:"A fault appears only after the machine has warmed and cycled.",revealed:false,resolved:false)]
  let days=[StartupCampaignDay(id:"DAY-1",day:1,title:"Installation & Cold Checks",objective:"Close field installation, loop checks, calibration and SAT evidence.",targetStage:.coldCommissioning,requiredRecords:["Loop checks","Calibration certificates","SAT"],faultEventIDs:["CF-1"]),.init(id:"DAY-2",day:2,title:"First Energization",objective:"Build and authorize the energization package, then perform controlled first power and motor solo runs.",targetStage:.energized,requiredRecords:["Permit to energize","LOTO restoration","Motor solo-run","Shift log"],faultEventIDs:["CF-2"]),.init(id:"DAY-3",day:3,title:"Hot Commissioning & Turnover",objective:"Prove stable production, train operations, turn over spares/maintenance records and close the final book.",targetStage:.production,requiredRecords:["Training sign-off","Turnover package","Maintenance handover","Final documentation book"],faultEventIDs:["CF-3"])]
  return .init(permit:permit,loto:loto,loopChecks:loops,calibrations:[cal],motorRuns:[motor],turnover:turnover,shiftLog:[],training:training,spares:spares,maintenance:maint,campaign:.init(id:"CAMPAIGN-STARTUP-01",title:"Three-Day Packaging Cell Startup",days:days,faults:faults,currentDay:1,instructorSeed:20260902,score:100))
 }
}
